version: '3'
services:
    app:
        container_name: API-Server
        restart: always
        build: .
        ports:
            - '3000:3000'
        links:
            - mongo
    
    mongo:
        container_name: mongoDB
        image: mongo
        ports:
            - '27017:27017'